"""add abs_synced_position_seconds to reading_progress

Revision ID: 846c2202fe28
Revises: 0003be688fd1
Create Date: 2026-08-06 07:25:13.987709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '846c2202fe28'
down_revision: Union[str, Sequence[str], None] = '0003be688fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abs_synced_position_seconds', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_column('abs_synced_position_seconds')

    # ### end Alembic commands ###
